/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
<<<<<<< HEAD
#define BUILD_DATE "Thu Apr  1 21:16:53 2021"
#define BUILD_TIME (1617311813L)
=======
#define BUILD_DATE "Fri Dec 13 02:52:53 2019"
#define BUILD_TIME (1576205573L)
>>>>>>> origin/kusohack

#define VERSION_NUMBER 0x03040300UL
#define VERSION_FEATURES 0x001e0cc6UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x211b117eUL
#define VERSION_SANITY2 0xb8d24950UL

#define VERSION_STRING "3.4.3"
#define VERSION_ID \
<<<<<<< HEAD
 "Unix NetHack Version 3.4.3 - last build Thu Apr  1 21:16:53 2021."
#define JVERSION_ID \
 "Unix JNetHack Version 0.11.0 - last build Thu Apr  1 21:16:53 2021."
=======
 "Unix NetHack Version 3.4.3 - last build Fri Dec 13 02:52:53 2019."
#define JVERSION_ID \
 "Unix JNetHack Version 0.11.0 - last build Fri Dec 13 02:52:53 2019."
>>>>>>> origin/kusohack

